### PR TITLE
hackoberfest contribution - mobile styling

### PR DESCRIPTION
**Pull request by MarissaWood**
I added media query to change the layout on mobile so all of the elements are stacked and fill the viewport width. 

It will change for portrait mode on all phones and landscape on most phones - but still displays the desktop version on larger phones in landscape mode.

### CODE REVIEW

**Comment by JS-goose** [comment]
Wow, that's awesome!  Thank you for your contribution but this one was taken care of with a previous PR 😄

**Comment by JS-goose** [comment]
I like the idea and effort thank you!  It looks like there are some conflicts with the code base though.  Would you mind to fix those before merge?

**Comment by MarissaWood** [comment]
Fixed the conflicts! It should be good to go now.  Happy Hacktoberfest!

**Comment by JS-goose** [comment]
Thank you so very much for your contribution!  

Happy Hacktoberfest!

**Pull request merged**
